spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/workflow}
    username: ${DB_USER:workflow}
    password: ${DB_PASSWORD:workflow}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
